### ISSUE TITLE
Miscellaneous GPU Enhancements

### ISSUE THREAD

**Issue by terrytangyuan** [tensorflow/skflow#107]
Questions collected from SO tagged with skflow:

- [x] Limit GPU memory allocation:
http://stackoverflow.com/questions/35483367/limit-gpu-memory-allocation-in-skflow/35485392#35485392

- [ ] Specify which GPU to use: 
http://stackoverflow.com/questions/35504528/skflow-allocates-memory-in-gpu0-even-when-other-gpu-is-specified

- [ ] More GPU options are hidden in [here](https://github.com/tensorflow/tensorflow/blob/65e48e88e17548e3116c3750dfd0b83c428e20ec/tensorflow/core/framework/config.proto) that you cannot find the current TF docs, let me know if there's anyone in particular you are interested in using.

**Comment by ilblackdragon** [comment]
@terrytangyuan  Let's either move to tensorflow/tensorflow or close this one as well.
