### ISSUE TITLE
Text Classification Examples Giving Error

### ISSUE THREAD

**Issue by newterminator** [tensorflow/skflow#112]
I downloaded both the [Text Classification Using Recurrent Neural Networks on Words](https://github.com/tensorflow/skflow/blob/master/examples/text_classification.py) example and the [Simplified Version Using Built-in RNN Model with easy to use built-in parameters](https://github.com/tensorflow/skflow/blob/master/examples/text_classification_builtin_rnn_model.py) example, and tried running both to see the output and then learn how to use _skflow_ from the code in the examples.

_Python Version: 2.7.11
Tensorflow version: 0.7.1
Scikit-learn version: 0.17.1_

I got the following error from running both the files separately: `NotImplementedError: Negative indices are currently unsupported`

I attached a quick pic showing the details of the error:

![skflow](https://cloud.githubusercontent.com/assets/5087437/13311266/f8c70ed2-db5a-11e5-970e-9d4b0379b69a.png)

**Comment by ilblackdragon** [comment]
The #119 PR is addressing this - the changes in 0.7.1 changed the `rnn` API in a bit (IMO) weird way.

**Comment by ilblackdragon** [comment]
Should be fixed after merge, please let me know!

**Comment by newterminator** [comment]
@ilblackdragon , I confirm it is fixed now. Thanks !
