### ISSUE TITLE
An AttributeError while running iris_save_restore.py  

### ISSUE THREAD

**Issue by ChihChengYang** [tensorflow/skflow#116]
** Traceback (most recent call last):
  File "iris_save_restore.py", line 26, in <module>
    new_classifier = skflow.TensorFlowEstimator.restore('/tmp/skflow_examples/iris_custom_model')
  File "/usr/lib/python3.4/site-packages/skflow/estimators/base.py", line 463, in restore
    estimator._restore(path)
  File "/usr/lib/python3.4/site-packages/skflow/estimators/base.py", line 401, in _restore
    saver_def = tf.python.training.saver_pb2.SaverDef()
AttributeError: 'module' object has no attribute 'saver_pb2'**
 
The location of saver_pb2.py seems to have been changed in the latest tensorflow ?
 #    saver_def = tf.python.training.saver_pb2.SaverDef() 
       saver_def = tf.core.protobuf.saver_pb2.SaverDef()

**Comment by terrytangyuan** [comment]
Yes please try the latest version. It's fixed in https://github.com/tensorflow/skflow/pull/108

**Comment by ChihChengYang** [comment]
Ok, Thank you...
