### ISSUE TITLE
Version check for tensorflow

### ISSUE THREAD

**Issue by ilblackdragon** [tensorflow/skflow#120]
We are removing support of older tensorflow versions (as their API is changing) so we should have a nice user-friendly message asking people to update their Tensorflow if they installed a new version of skflow with older tensorflow.

Maybe just check on the import in `__init__.py`

**Comment by drcrook1** [comment]
Is there a way to cmd line check the version of tensor flow or via python code?

**Comment by terrytangyuan** [comment]
This kind of question is more suitable in stackoverflow. This repo is being removed soon. Please go to TensorFlow repo. Thanks.

**Comment by Deepak5j** [comment]
for windows (cmd)
C:\WINDOWS\system32>python
>>> import tensorflow as tf
>>> print(tf.__version__)
0.12.1
>>>

**Comment by andlyu** [comment]
is there a way of checking whether it is gcp
