### ISSUE TITLE
Support loading pre-trained model parts

### ISSUE THREAD

**Issue by HiuNaoki** [tensorflow/skflow#122]
i want to using autoencoder for pre-training in skflow....

please help me..

**Comment by ilblackdragon** [comment]
Currently it's not very simple at all.
The easiest way, would be to dump numpy arrays from the pre-trained model (using `get_tensor_value` method on estimator) and then use `initializer` for your variables in your target model.

I'll make it easier, but sklearn doesn't have anything remote to API for this, so will need to think carefully to have something that would be useable in years to come.

**Comment by ilblackdragon** [comment]
Here is suggested API: https://github.com/tensorflow/tensorflow/issues/2141 and will track this functionality there.
