### ISSUE TITLE
Text classification - How to save VocabularyProcessor after fit?

### ISSUE THREAD

**Issue by prasanna513** [tensorflow/skflow#130]
To later run the saved model on test data, I need to save the VocabularyProcessor after I fit with the training data. How do I save it? Thanks, Prasanna

**Comment by terrytangyuan** [comment]
You can dump it to JSON file. @ilblackdragon Do you think it's worth making those serializable or implementing serializer method?

**Comment by prasanna513** [comment]
Save and restore methods on this too will be helpful I think. Thanks for the quick reply.

**Comment by ilblackdragon** [comment]
You can just pickle the object. I'll add save and restore methods though.
