### ISSUE TITLE
L2 Regularization

### ISSUE THREAD

**Issue by viveksembium** [tensorflow/skflow#139]
Is there an easy way to enable L2 Regularization to the skflow DNN classifier? Or is L2 enabled by default?

**Comment by ilblackdragon** [comment]
L2 regularization for learnable variables? Right now the easiest way would be to use custom model and add regularizer (from tensorflow) things - you can also add an option to TensorFlowDNN* estimator as a PR.

**Comment by terrytangyuan** [comment]
There's L2 regularization layer you can use in custom model from tensorflow.contrib.layers.
