### ISSUE TITLE
specifying sequence lengths

### ISSUE THREAD

**Issue by mheilman** [tensorflow/skflow#141]
Currently, it's not very clear how to use the sequence length functionality in `TensorFlowRNNClassifier` ([link](https://github.com/tensorflow/skflow/blob/f933c9956ee54dab78cae9ff83b11c2d09eebd8a/skflow/estimators/rnn.py#L40)).  This currently takes a tensor as an argument, since the argument is eventually passed along to `tensorflow.nn.rnn`, which expects an integer tensor.  However, it's not clear how one would define that sequence length tensor since the input placeholder, from which one would compute it, is defined in the `fit` method using [_setup_training](https://github.com/mheilman/skflow/blob/71a31557a00af6e390a327fa405bcfe148eb3f98/skflow/estimators/base.py#L127).

It seems like maybe `sequence_length` should take a function whose input is the input placeholder and whose output is a tensor, rather than taking a tensor directly, similar to how the `input_op_fn` argument works.

If there is some way currently to use the `sequence_length` argument to specifying the sequence lengths for items in a minibatch, it'd be great to have an example using it.  Currently, the examples don't use sequence lengths ([example](https://github.com/mheilman/skflow/blob/71a31557a00af6e390a327fa405bcfe148eb3f98/examples/text_classification_builtin_rnn_model.py#L64)), which I think means that the RNN just reads in 0s at the ends of inputs that are padded up to the maximum sequence length.

**Comment by mheilman** [comment]
[Here](https://github.com/mheilman/skflow/commit/71a31557a00af6e390a327fa405bcfe148eb3f98) is what I was thinking with respect to the sequence length argument being a function.

**Comment by terrytangyuan** [comment]
Please consider submitting a PR to TensorFlow repo to fix this or add additional example. Thanks!
