### ISSUE TITLE
Tensorflow GPU version support with skflow

### ISSUE THREAD

**Issue by vnkmr7620** [tensorflow/skflow#146]
I have been trying to execute text_classification.py example of skflow but it is generating an error. Please see the attached document for an error as well as the version of tensorflow and the skflow.  Th error is     **tensorflow.python.framework.errors.InvalidArgumentError: Cannot assign a device to node 'train/update_words/words_embeddings/Assign_1': Could not satisfy explicit device specification '' because the node was colocated with a group of nodes that required incompatible device '/job:localhost/replica:0/task:0/GPU:0'
![error](https://cloud.githubusercontent.com/assets/10511526/13720749/cb5b3c8c-e836-11e5-8377-23323c86eab4.png)
![version](https://cloud.githubusercontent.com/assets/10511526/13720753/dc4a1ebe-e836-11e5-8670-4f06bc29145b.png)
**

**Comment by terrytangyuan** [comment]
You need to update your tensorflow.
