### ISSUE TITLE
Getting probability from DNNclassifier

### ISSUE THREAD

**Issue by victoyip** [tensorflow/skflow#147]
In addition to getting the predicted label, I would like to access the probability associated with each prediction. Can I do that with this classifier?

**Comment by terrytangyuan** [comment]
Use pred_proba instead of predict.

**Comment by victoyip** [comment]
It said DNNClassifer has no such attribute?


`AttributeError: 'TensorFlowDNNClassifier' object has no attribute 'pred_proba'`

**Comment by terrytangyuan** [comment]
Sorry it should be predict_proba.
