### ISSUE TITLE
Can't restore my model

### ISSUE THREAD

**Issue by syx114** [tensorflow/skflow#149]
when i use TensorFlowEstimator.restore(...) , it shows "name 'TensorFlowEstimator' is not defined"
and skflow.TensorFlowEstimator.restore(...) shows " 'module' object has no attribute 'saver_pb2' "

**Comment by ilblackdragon** [comment]
Can you also give stack trace? And version of tensorflow?

**Comment by terrytangyuan** [comment]
There has been a lot of bug fixes since 0.8. Please try latest version. Please submit an issue to TensorFlow repo in the future instead.
