### ISSUE TITLE
Small suggestion for default value of keep_checkpoint_every_n_hours

### ISSUE THREAD

**Issue by kootenpv** [tensorflow/skflow#151]
I was not understanding the default value of 10000 (it's not obvious if I was misunderstanding it, or if it is just never going to do it)

https://github.com/tensorflow/skflow/blob/master/skflow/estimators/dnn.py#L57

I would suggest default value of 0 which means never.

**Comment by terrytangyuan** [comment]
Well, 10000 is 416.67 days - nobody's going to do that so it's the same as "never". We followed this default value from TensorFlow. Maybe there's some internal stuff going on there so 0 might mean something different, e.g. trying to save it just once. Have to check in TensorFlow internally though.

**Comment by kootenpv** [comment]
Ah my bad, didn't know tensorflow came up with that default. I guess it's good to stick to their default. That said, I do believe it is a confusing default. `None` or `0` would be clearer in my opinion. Or something more ridiculous like `10000000`. But that's for tensorflow :-)

**Comment by terrytangyuan** [comment]
No problem. FYI, we recently moved skflow to TF [here](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/skflow).
