### ISSUE TITLE
update trained model

### ISSUE THREAD

**Issue by kengz** [tensorflow/skflow#153]
currently calling 
```python
classifier.fit(X_train1, y_train1)
classifier.fit(X_train2, y_train2)
```
resets the classifier and train it on training set 2. Is there a way to "resume training"?

Example use case would be getting the next batch of training data next, or do on-line training, e.g. incoming new labeled data while the model is deployed.

**Comment by terrytangyuan** [comment]
There's a `continue_training` parameter you can use. Take a look at some examples, in particular [this] (https://github.com/tensorflow/skflow/blob/master/examples/text_classification.py) one.

**Comment by kengz** [comment]
exactly what I'm looking for. Thanks!
