### ISSUE TITLE
TypeError: List of Tensors when single Tensor expected

### ISSUE THREAD

**Issue by michael4john** [tensorflow/skflow#154]
Running text_classification.py and text_classification_character_rnn.py, which I just downloaded, on shell both returned me the following error:

> TypeError: List of Tensors when single Tensor expected

Below is the snippet:
![typeerror](https://cloud.githubusercontent.com/assets/16963717/14068025/621ead16-f444-11e5-80e0-945bd6cbedc9.PNG)

The weird thing is running text_classification that I downloaded several months ago did NOT return me this kind of error.

Any advice will be appreciated.

**Comment by GameOfThrow** [comment]
can you specify the version of your TensorFlow package?

**Comment by michael4john** [comment]
I should have included this in the above. Below is the version info:

Tensorflow: 0.6.0
Python: 2.7.6
Numpy: 1.10.4

**Comment by terrytangyuan** [comment]
Try most updated version of tensorflow and skflow

**Comment by GameOfThrow** [comment]
yes, it's just a matter of getting the latest package, update Tensorflow and skflow should work fine.

**Comment by terrytangyuan** [comment]
This should be just version issue. Closing now but feel free to re-submit the issue on TensorFlow repo.
