### ISSUE TITLE
installation script for OpenBLAS

### ISSUE THREAD

**Issue by kengz** [tensorflow/skflow#155]
Skflow makes it much easier and faster to get into ML. There's some blas libraries specified in the `.travis.yml`. 

Would it be possible also to automatically download, build, install and link OpenBLAS (or any relevant ones) through a shell script that comes with skflow? This would allow many users to run more performant and efficient operations too.

**Comment by ilblackdragon** [comment]
Installation of OpenBLAS is very system specific. Skflow relies on one
having scipy installed, which in turn requires some version of BLAS
installed.

The easiest way for all this to be installed in system independent way is
Docker. Skflow recently moved into main tensorflow codebase, so it will be
available in next version of tensorflow dockers. I'll try to have Docker
that have all the dependencies installed.

For now may be documenting more about dependencies would be a good idea. Or
if you are interested in helping with script like you mentioned - that will
be highly appreciated.

**Comment by kengz** [comment]
I see. The TF Docker approach is prolly the most convenient, especially if it can come already optimized. I currently have bash setup scripts for 2 OSes (MacOSX and Ubuntu Trusty) for my project which also uses skflow. 

The Ubuntu version has the blas libraries listed in the skflow installation script; the MacOSX does not yet have it installed and setup. I'm looking at OpenBLAS for it, not sure if there's a more appropriate one.

I can share and complete the said script if it's helpful, what do you think?

**Comment by ilblackdragon** [comment]
Feel free to share script at https://github.com/tensorflow/tensorflow. Closing this issue (skflow has been moved inside TensorFlow).
