### ISSUE TITLE
Exception when running language model example

### ISSUE THREAD

**Issue by savkov** [tensorflow/skflow#156]
Hi,

Thanks for making this tool. It will definitely make things easier for NN newcomers.

I just tried running your [language model example](https://github.com/tensorflow/skflow/blob/master/examples/language_model.py) and got the following exception:

```
Traceback (most recent call last):
  File "test.py", line 84, in <module>
    estimator.fit(X, y)
  File "/Users/aleksandar/tensorflow/lib/python3.5/site-packages/skflow/estimators/base.py", line 243, in fit
    feed_params_fn=self._data_feeder.get_feed_params)
  File "/Users/aleksandar/tensorflow/lib/python3.5/site-packages/skflow/trainer.py", line 114, in train
    feed_dict = feed_dict_fn()
  File "/Users/aleksandar/tensorflow/lib/python3.5/site-packages/skflow/io/data_feeder.py", line 307, in _feed_dict_fn
    inp[i, :] = six.next(self.X)
StopIteration
```
I made sure that my python distribution has the correct version of `six`. I tried running it both in a virtual environment and in a normal Python 3 distro. Any ideas what might be causing this?

**Comment by GameOfThrow** [comment]
could be a tensorflow/skflow version issue, can you specify the version/check for updates?

**Comment by mmarklar** [comment]
I'm also getting the same exception on Tensorflow 0.7.1 and Skflow 0.1.0

Also tried with nightly of TF using the contrib.skflow, same result. Let me know if anything else would be useful.

**Comment by mdasadul** [comment]
I am also getting same error as well

**Comment by ilblackdragon** [comment]
Hi,

Sorry for slow response.

Can you try doing `print(six.next(X))` in `language_model.py` before `### Model` section? To just see what happen with data.
On Python2 seems to work, I'll double check on Python3.

**Comment by rasmushaglund** [comment]
I'm getting the same error in both 0.8 and 0.9rc1. @ilblackdragon when running the above command before the model section it works fine, but then fails as usual.
I'm running Python 2.7

**Comment by rasmushaglund** [comment]
I tried finding the source, and this is what I found: https://github.com/tensorflow/tensorflow/commit/30573c21e067ad7ec2bd74c062505d0506a36d57#commitcomment-17868872

**Comment by ilblackdragon** [comment]
This may be fixed now with refactoring to use MonitoredSession.

If not, please re-file bug at tensorflow repository - this one is inactive. Thanks!
