### ISSUE TITLE
seq2seq example doesn't work

### ISSUE THREAD

**Issue by stylianos-kampakis** [tensorflow/skflow#166]
The line    

decoding, _, sampling_decoding, _ = skflow.ops.rnn_seq2seq(in_X, in_y,encoder_cell, decoder_cell=decoder_cell)

does not seem to follow the function's declaration:

def rnn_seq2seq(encoder_inputs, decoder_inputs, cell, dtype=tf.float32, scope=None):

**Comment by ilblackdragon** [comment]
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/learn/python/learn/ops/seq2seq_ops.py has the functions definition matching example:

```
def rnn_seq2seq(encoder_inputs, decoder_inputs, encoder_cell, decoder_cell=None,
                dtype=dtypes.float32, scope=None):
```
