### ISSUE TITLE
text_classification.py giving error

### ISSUE THREAD

**Issue by aroradeepak001** [tensorflow/skflow#170]
I am just trying to run this example as it is, It is giving me following error : 

 File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/ops.py", line 462, in __bool__
    raise TypeError("Using a `tf.Tensor` as a Python `bool` is not allowed. "
TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed. Use `if t is not None:` instead of `if t:` to test if a tensor is defined, and use the logical TensorFlow ops to test the value of a tensor.

**Comment by ilblackdragon** [comment]
Hi @aroradeepak001,

Please use skflow from Tensorflow 0.8 - it got moved and already released there. All the issues as such one are fixed there. You can just install Tensorflow 0.8 and import skflow as `import tensorflow.contrib.learn as skflow`.

**Comment by aroradeepak001** [comment]
Hey 
Thank you for such a quick response , Cheers!!
