### ISSUE TITLE
Scikitflow documentation update requested

### ISSUE THREAD

**Issue by kingkastle** [tensorflow/skflow#178]
[Scikitflow readme.md](https://github.com/tensorflow/skflow) file needs to update its examples, for example, check this [StackOverflow question](http://stackoverflow.com/questions/38120008/anaconda-tensorflow-skflow-dnn-got-an-unexpected-keyword-argument-keep-p/38120728#38120728)

Thanks!

**Comment by terrytangyuan** [comment]
It's now hosted here: https://www.tensorflow.org/versions/master/api_docs/python/contrib.learn.html#learn-contrib
