### ISSUE TITLE
neural_translation.py showing error

### ISSUE THREAD

**Issue by vinayakumarr** [tensorflow/skflow#180]
I was trying to execute neural_translation.py but it is generating the below error
![untitled](https://cloud.githubusercontent.com/assets/18217467/17458252/aa3385a2-5c29-11e6-8cd4-90113fca1e45.png)

**Comment by unsalted** [comment]
same issue any luck figuring it out?

**Comment by vinayakumarr** [comment]
No.

**Comment by vinayakumarr** [comment]
You can try to with tensorflow 0.7 and skflow 1 version

**Comment by ilblackdragon** [comment]
Please re-file bug at tensorflow repository - this one is inactive. Thanks!
