### ISSUE TITLE
Tensor name "hiddenlayer_2/biases" not found in checkpoint files

### ISSUE THREAD

**Issue by eymar** [tensorflow/skflow#182]
I have created my model on one machine and then sent the zipped folder 'model' by email to myself so I would be able to use this model on my second PC. 

Here is the code how I'm recreating a model:
```
feature_columns = learn.infer_real_valued_columns_from_input(x_train)
classifier = learn.DNNClassifier(feature_columns=feature_columns, hidden_units=[40, 80, 40], n_classes=3, model_dir='model')
```

As I understood, to reuse a model I need to make 'fit' 1-3 steps. (This fact I found here in TF issues)

`classifier.fit(x_train, y_train, steps=3)`

Then when I call `predicted = classifier.predict(x_test)` , it throws an exception:  
tensorflow.python.framework.errors.NotFoundError: Tensor name "hiddenlayer_2/biases" not found in checkpoint files model/model.ckpt-30015-?????-of-00001

This model is working well on the machine where it has been created. 
How can I make it work on any PC?

Thanks!

**Comment by ilblackdragon** [comment]
Please re-file bug at tensorflow repository - this one is inactive. Thanks!
