### ISSUE TITLE
Add functionality to construct and train RNNs

### ISSUE THREAD

**Issue by ecoskian** [tensorflow/skflow#5]
As per title, it would be great to have the ability to build and train RNNs easily with this library.

**Comment by ilblackdragon** [comment]
It's currently possible to train RNNs (see text_classification* examples), but it would be nice to have semi-generic `RNNClassifier` / `RNNRegressor`.

**Comment by terrytangyuan** [comment]
@ecoskian Just added this functionality. 
See https://github.com/tensorflow/skflow/blob/master/examples/text_classification_builtin_rnn_model.py
You can also change the `cell_type` to what you need, e.g. rnn, gru, and lstm.
