### ISSUE TITLE
DataFeeder: Sampling without replacement

### ISSUE THREAD

**Issue by makseq** [tensorflow/skflow#50]
Hi, 

1) I suspect there is a error in _feed_dict_fn. 
Why don't you save used sample indices? They could be repeated when you call _feed_dict_fn() again in the same epoch. 
sample = random.randint(0, self.X.shape[0] - 1)
inp[i, :] = self.X[sample, :]

2) It is not an epoch but only one step for one batch. 
for step in xrange(steps):
          feed_dict = feed_dict_fn()
          global_step, loss, _ = sess.run([self.global_step, self.loss, self.trainer], feed_dict=feed_dict)

I think, it must be something like this: 
    for step in xrange(steps):
       for i in xrange(X.shape[0]/batch_size):
          feed_dict = feed_dict_fn()
          global_step, loss, _ = sess.run([self.global_step, self.loss, self.trainer], feed_dict=feed_dict)

Am I right? Or I have an incorrect guess?

**Comment by boscotsang** [comment]
Here are some opinions of mine. For the first question, I think in "sgd" each batch is random sampled so the _ffed_dict_fn() should be repeated called. I agree with you in the second question.

**Comment by ilblackdragon** [comment]
In general, I agree that epochs should be used and non-repeated data, but right now it is indeed just trains specified a number of randomly sampled batches.

If somebody has time to implement a proper sampler for epochs (e.g. generate random indexes to sample into batches and then run over them) - I'll greatly appreciate the help! :)

**Comment by makseq** [comment]
I will have time to implement it if somebody adds me to contributors :) maybe it'll be a little help with my future migration to Google :))

**Comment by ilblackdragon** [comment]
@makseq Feel free as part of your PR add yourself to `CONTRIBUTORS` and `AUTHORS` files. I though personally like this page a lot - https://github.com/google/skflow/graphs/contributors 

PS. Let me know if you are interested in referral to G :)

**Comment by makseq** [comment]
Ok, thank you a lot. I will do it on holidays :)

**Comment by ilblackdragon** [comment]
Solved by @makseq in #b14b86c Thanks!
