### ISSUE TITLE
Example of language model

### ISSUE THREAD

**Issue by ilblackdragon** [tensorflow/skflow#64]
Add an example of language model (RNN). For example character level on sheikspear book (similar to https://github.com/sherjilozair/char-rnn-tensorflow).

**Comment by ilblackdragon** [comment]
Added a simple character language model in #74

**Comment by evanmiltenburg** [comment]
Any chance of an RNN/LSTM example for labeling tasks as well? (E.g. [sentiment analysis](http://www.cs.cornell.edu/~oirsoy/files/emnlp14drnt.pdf) or [NER](http://www.aclweb.org/anthology/W03-0426))

**Comment by ilblackdragon** [comment]
Hi Emiel, the sentiment analysis can be done from text_classification
examples (sentiment is just a two or five class document classification).
NER is more like language model structure. We should add some concrete
examples though with datasets though over time.

**Comment by evanmiltenburg** [comment]
Cool, thanks!

**Comment by eldor4do** [comment]
Hi, not a related comment, but how do I go about doing multi label image classification using skflow? Do I do something similar to the multioutput code?

**Comment by ilblackdragon** [comment]
@eldor4do For multi label classification - you can just pass a number of active classes to the model - e.g. y to be a matrix [examples, n_classes]. You just need to decide on your loss in the function, regular Estimators may not work very well as this point.

**Comment by ilblackdragon** [comment]
Closing this issue as language model is in repository in limited capacity.
